# Generated by Django 4.2.1 on 2023-11-30 12:29

from django.db import migrations, models
import django.db.models.deletion
import equipment.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=equipment.models.Machine.machine_file_path)),
                ('machine_status', models.TextField(choices=[('OPERATED', 'Эксплуатируется'), ('UNDER_REPAIR', 'В ремонте'), ('DECOMMISSIONED', 'Списано')], default='OPERATED')),
                ('workshop_number', models.CharField(blank=True, null=True)),
                ('span_number', models.IntegerField(default=1)),
            ],
            options={
                'verbose_name_plural': 'Оборудование',
                'db_table': 'Machine',
            },
        ),
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.TextField(choices=[('HORIZONTAL_BORING_MACHINE', 'Горизонтально - расточные станки'), ('SCREW_CUTTING_MACHINE', 'Токарно - винторезные станки'), ('TURNING_LATHES_MACHINE', 'Токарно - карусельные станки'), ('FORGING_STAMPING_EQUIPMENT', 'Кузнечно - штамповочное оборудование'), ('HANDLING_EQUIPMENT', 'Подъемно - транспортное оборудование'), ('OTHER', 'ДРУГОЕ')], unique=True)),
            ],
            options={
                'verbose_name_plural': 'Группы',
                'db_table': 'MachineGroup',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.TextField(default='test', max_length=500, null=True)),
                ('status', models.TextField(choices=[('OPEN', 'Открыто'), ('FULFILLED', 'Исполнено'), ('NOT_RELEVANT', 'Неактуально'), ('DRAFT', 'Черновик')], default='OPEN')),
                ('file_name', models.CharField(blank=True, max_length=90, null=True)),
                ('order_file_path', models.FileField(null=True, upload_to=equipment.models.Orders.orders_file_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine', to='equipment.machine')),
            ],
            options={
                'verbose_name_plural': 'Заявки',
                'db_table': 'Orders',
            },
        ),
        migrations.AddField(
            model_name='machine',
            name='equipment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_group', to='equipment.machinegroup'),
        ),
    ]
