# Generated by Django 4.2.1 on 2023-11-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_number', models.CharField(max_length=50, null=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='machine',
            name='equipment_workshop_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_workshop_number', to='equipment.workshopnumber'),
        ),
    ]
