# Generated by Django 4.2.1 on 2023-07-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='machine',
            table='Оборудование',
        ),
    ]
