# Generated by Django 4.2.1 on 2023-07-08 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_alter_machine_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='orders',
            table='Заявки',
        ),
    ]
