# Generated by Django 4.2.1 on 2023-07-08 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_orders_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='machine',
            table='custom_orders',
        ),
    ]
