# Generated by Django 4.2.1 on 2023-11-30 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_alter_workshopnumber_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='workshopnumber',
            options={'verbose_name_plural': 'Наименова́ние(номер) корпуса'},
        ),
    ]
