# Generated by Django 4.2.1 on 2023-07-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_alter_machine_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='machine',
            options={'verbose_name_plural': 'Оборудование'},
        ),
        migrations.AlterModelTable(
            name='machine',
            table='Оборудование',
        ),
    ]
