# Generated by Django 4.2.1 on 2023-07-08 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_alter_machine_options_alter_machine_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={'verbose_name_plural': 'Заявки'},
        ),
        migrations.AlterModelTable(
            name='machine',
            table='Machine',
        ),
        migrations.AlterModelTable(
            name='orders',
            table='Orders',
        ),
    ]
