# Generated by Django 4.2.1 on 2023-07-08 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_orders_options_alter_machine_table_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos/machines/'),
        ),
    ]
