# Generated by Django 4.2.1 on 2023-11-30 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_alter_workshopnumber_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='equipment_workshop_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_workshop_number', to='equipment.workshopnumber', to_field='workshop_number'),
        ),
    ]
