# Generated by Django 4.2.1 on 2023-07-08 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_alter_machine_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/machines/'),
        ),
    ]
