# Generated by Django 4.2.1 on 2023-12-01 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_remove_machine_workshop_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpanNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('span_number', models.IntegerField(null=True, unique=True)),
            ],
            options={
                'verbose_name_plural': 'Номер пролёта',
                'db_table': 'SpanNumber',
            },
        ),
    ]
