# Generated by Django 4.2.1 on 2023-07-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0008_alter_machine_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='group',
            field=models.TextField(choices=[('HORIZONTAL_BORING_MACHINE', 'Горизонтально - расточной станок'), ('', 'Кузнечно - штамповочное оборудование'), ('OTHER', 'ДРУГОЕ')], default='OTHER'),
        ),
    ]
