# Generated by Django 4.2.1 on 2023-12-01 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0009_spannumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='equipment_span_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='machine_span_number', to='equipment.spannumber', to_field='span_number'),
        ),
    ]
