# Generated by Django 4.2.1 on 2023-12-01 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_machine_equipment_span_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='machine',
            name='span_number',
        ),
    ]
