# Generated by Django 4.2.1 on 2023-07-12 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0010_alter_machine_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='orders_files',
            field=models.FileField(null=True, upload_to='orders/<django.db.models.fields.related.ForeignKey>/'),
        ),
    ]
