# Generated by Django 4.2.1 on 2023-12-01 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0011_remove_machine_span_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='reason',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
