# Generated by Django 4.2.1 on 2023-07-18 10:16

from django.db import migrations, models
import equipment.models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0012_alter_orders_orders_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=equipment.models.Machine.machine_file_path),
        ),
        migrations.AlterField(
            model_name='orders',
            name='orders_files',
            field=models.FileField(null=True, upload_to=equipment.models.Orders.orders_file_path),
        ),
    ]
