# Generated by Django 4.2.1 on 2023-08-21 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0013_alter_machine_photo_alter_orders_orders_files'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='group',
            field=models.TextField(choices=[('HORIZONTAL_BORING_MACHINE', 'Горизонтально - расточные станки'), ('TURNING_MILLING_MACHINE', 'Токарно - фрезерные станки'), ('FORGING_STAMPING_EQUIPMENT', 'Кузнечно - штамповочное оборудование'), ('OTHER', 'ДРУГОЕ')], default='OTHER'),
        ),
    ]
