# Generated by Django 4.2.1 on 2023-12-01 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0015_alter_orders_order_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='order_reason',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_reason', to='equipment.reason', to_field='reason'),
        ),
    ]
