# Generated by Django 4.2.1 on 2023-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0016_alter_machine_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='group',
            field=models.TextField(choices=[('HORIZONTAL_BORING_MACHINE', 'Горизонтально - расточные станки'), ('SCREW_CUTTING_MACHINE', 'Токарно - винторезные станки'), ('TURNING_LATHES_MACHINE', 'Токарно - карусельные станки'), ('FORGING_STAMPING_EQUIPMENT', 'Кузнечно - штамповочное оборудование'), ('HANDLING_EQUIPMENT', 'Подъемно - транспортное оборудование'), ('OTHER', 'ДРУГОЕ')], default='OTHER'),
        ),
    ]
