# Generated by Django 4.2.1 on 2023-12-09 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_alter_orders_order_reason'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='reason',
        ),
    ]
