# Generated by Django 4.2.1 on 2023-10-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0017_alter_machine_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='machine',
            name='factory_floor',
            field=models.IntegerField(max_length=1000, null=True),
        ),
    ]
