# Generated by Django 4.2.1 on 2023-12-09 13:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0018_remove_orders_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.TextField(max_length=1000)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='equipment.orders')),
            ],
            options={
                'verbose_name_plural': 'Пункты',
                'db_table': 'OrderItems',
            },
        ),
    ]
