# Generated by Django 4.2.1 on 2023-10-07 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_alter_machine_factory_floor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machine',
            name='factory_floor',
            field=models.IntegerField(default=1),
        ),
    ]
