# Generated by Django 4.2.1 on 2023-12-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0019_orderitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='item',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
