# Generated by Django 4.2.1 on 2023-12-09 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_alter_orderitems_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitems',
            name='quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='orderitems',
            name='unit',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
