# Generated by Django 4.2.1 on 2023-11-14 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0020_alter_machine_factory_floor'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineGroup',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('group', models.TextField(choices=[('HORIZONTAL_BORING_MACHINE', 'Горизонтально - расточные станки'), ('SCREW_CUTTING_MACHINE', 'Токарно - винторезные станки'), ('TURNING_LATHES_MACHINE', 'Токарно - карусельные станки'), ('FORGING_STAMPING_EQUIPMENT', 'Кузнечно - штамповочное оборудование'), ('HANDLING_EQUIPMENT', 'Подъемно - транспортное оборудование'), ('OTHER', 'ДРУГОЕ')], unique=True)),
            ],
            options={
                'verbose_name_plural': 'Группы',
                'db_table': 'MachineGroup',
            },
        ),
        migrations.RemoveField(
            model_name='machine',
            name='group',
        ),
        migrations.AddField(
            model_name='machine',
            name='factory_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='orders',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='machine',
            name='equipment_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='equipment_group', to='equipment.machinegroup'),
        ),
    ]
