# Generated by Django 4.2.1 on 2023-12-25 04:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0022_alter_orders_order_reason_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='order_number',
            field=models.IntegerField(default=1, verbose_name='Номер заявки в текущем году.'),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_reason',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='orders_reason', to='equipment.reason', to_field='reason'),
        ),
    ]
